language: sh
cache: apt
env:
  - LINT=true
  - SHELL=bash
  - SHELL=dash
  - SHELL=ksh
  - SHELL=zsh
matrix:
  fast_finish: true
  include:
    - env:
        - SHELL=bash
      os: osx
script:
  - |
    if [ -n "${LINT}" ]; then
      shellcheck -s sh bin/shpec  # 'sh' refers to POSIX
    else
      $SHELL bin/shpec
    fi
before_install:
  - |
    install_shellcheck() {
      (
      for v; do
        pkg=shellcheck_${v}_amd64.deb
        url="http://ftp.debian.org/debian/pool/main/s/shellcheck/"
        wget $url/$pkg || continue
        echo "Installing $pkg"
        sudo dpkg -i $pkg
        break
      done
      )
    }
    install_shell() {
      echo "Installing $SHELL"
      sudo apt-get update -qq
      sudo apt-get install -y $SHELL
    }

    if [ "${SHELL}" = "zsh" ]; then
      echo "disable -r end; setopt sh_word_split" >> $HOME/.zshenv
    fi

    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      if [ -n "${LINT}" ]; then
        install_shellcheck 0.3.5-3 0.3.4-3
      elif ! type $SHELL > /dev/null; then
        install_shell
      fi
    fi
